"""add document_chunks table

Revision ID: 19dfaeab2f5a
Revises: a1b2c3d4e5f6
Create Date: 2026-03-27 15:54:31.881620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19dfaeab2f5a'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('workflow_instances_document_id_key'), 'workflow_instances', type_='unique')
    op.drop_index(op.f('ix_workflow_instances_document_id'), table_name='workflow_instances')
    op.create_index(op.f('ix_workflow_instances_document_id'), 'workflow_instances', ['document_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_instances_document_id'), table_name='workflow_instances')
    op.create_index(op.f('ix_workflow_instances_document_id'), 'workflow_instances', ['document_id'], unique=False)
    op.create_unique_constraint(op.f('workflow_instances_document_id_key'), 'workflow_instances', ['document_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
